@url_dev =  http://localhost:8888/v1/api


### signup
POST {{url_dev}}/user/signup
Content-Type: application/json

{
    "name": "Mudrik",
    "email": "Mudrik@chelsea.com",
    "password": "111"
}   